version: '3.7'

services:
  laravel:
    build:
      context: ./laravel
    volumes:
      - laravel:/var/www

  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    volumes:
      - laravel:/var/www

  php-fpm:
    image: php:fpm-alpine
    volumes:
      - laravel:/var/www

volumes:
  laravel:
